guild_chat_format: "<green>[GuildChat] </green><aqua><%player_name%></aqua> %message%"
heart_place_range: 384 # 16*24 blocks
tablist:
  header:
    - "        <gold>»»» GILDIE SOKOWY «««</gold>        "
    - ""
  footer:
    - ""
    - "        <blue>Ping: %player_ping%ms</blue> | <green>GRACZY ONLINE: %server_onlinecount%</green>        "
    - "<gold>Gildia: %guild_name%</gold>"
    - "<white>Bank: </white><gold>%guild_bank%</gold>"
bank_materials:
  IRON_INGOT: 1
  GOLD_INGOT: 2
  DIAMOND: 20
  EMERALD: 5
  NETHERITE_SCRAP: 50
spawn: # some random coordinates I use for testing, you should put yours!
  world: world
  x1: -36
  z1: 210
  x2: 0
  z2: 241
upgrades:
  WORKING_RADIUS:
    name: "Working radius"
    description: "The heart main working radius, in multiples of 16"
    icon: SMITHING_TABLE
    slot: 19
    level_prices:
      - 0
      - 50
      - 100
      - 500
      - 1000
  WARNING_RADIUS:
    name: "Warning radius"
    description: "The heart warning radius, in multiples of 16"
    icon: ENDER_EYE
    slot: 20
    level_prices:
      - 100
      - 500
      - 1000
  HEAL_RADIUS:
    name: "Healing radius"
    description: "The heart healing radius, in multiples of 16"
    icon: AMETHYST_CLUSTER
    slot: 21
    level_prices:
      - 100
      - 500
      - 1000
      - 1500
  MINING_FATIGUE:
    name: "Mining fatigue level"
    description: "The level of mining fatigue effect, applied in the working radius"
    icon: MINER_POTTERY_SHERD
    slot: 22
    level_prices:
      - 100
      - 500
      - 1000
  SLOWNESS:
    name: "Slowness level"
    description: "The level of slowness effect, applied in the working radius"
    icon: MUD
    slot: 23
    level_prices:
      - 100
      - 500
      - 1000
  CHEST_LOCK:
    name: "Chest locking"
    description: "Chest locking, applied in the working radius"
    icon: CHEST
    slot: 24
    level_prices:
      - 1000
items:
  GUILD_COMPASS:
    slot: 38
    cost: 2000
  GUILD_HEART:
    slot: 42
    cost: 2000

tpa_delay: 5
tpa_cost: 10
back_cost: 20
messages:
  no_permission: "<red>Nie masz uprawnień, by to zrobić!</red>"
  tpa:
    usage: "<yellow>Użycie: /%command% <gracz></yellow>"
    no_target: "<red>Nie znaleziono gracza.</red>"
    target_yourself: "<yellow>Nie możesz teleportować się do siebie.</yellow>"
    already_requested: "<yellow>Już wysłałeś TPA. Możesz je anulować <blue><click:run_command:'/tpcancel %targetplayer_name%'>/tpcancel %targetplayer_name%</click></blue></yellow>"
    timeout: "<yellow>Upłynął limit czasu twojego TPA!</yellow>"
    received_tp_request: "<gold><aqua>%player_name%</aqua> wysłał do ciebie TPA. <green><click:run_command:'/tpaccept %player_name%'>AKCEPTUJ</click></green> | <red><click:run_command:'/tpdeny %player_name%'>ODRZUĆ</click></red></gold>"
    sending_tp_request: "<green>Wysyłanie TPA do <aqua>%targetplayer_name%</aqua>. Możesz je anulować </green><blue><click:run_command:'/tpcancel %targetplayer_name%'>/tpcancel %targetplayer_name%</click></blue>"
    cancelled: "<green>TPA anulowane.</green>"
    no_request: "<red>Nie masz żadnych oczekujących TPA.</red>"
    tp_start: "<green>Teleportuję w ciągu 5 sekund... Nie ruszaj się.</green>"
    accepted_sender: "<aqua>%player_name%</aqua> <green>zaakceptował twoje TPA.</green>"
    accepted_player: "<green>Zaakceptowałeś TPA.</green>"
    rejected_sender: "<green>Twoje TPA zostało odrzucone!</green>"
    rejected_player: "<green>Odrzuciłeś TPA!</green>"
    no_back: "<red>Nie masz gdzie się cofać.</red>"
    death: "<yellow>ZDECHŁEŚ na X: %player_x% Y: %player_y% Z: %player_z%! Możesz się cofnąć za pomocą /back, jednak kosztuje to <gold>20</gold> banku</yellow>"
    moved: "<red>Ruszyłeś się, nic cię to nie kosztuje, ale nie będzie teleportu.</red>"
    guild_required: "<red>Do TPA potrzebujesz banku gildii.</red>"
    cannot_afford: "<red>Nie stać cię na to. Koszt TPA: <gold>10</gold>; Koszt /back: <gold>20</gold></red>"
    broadcast: "<aqua>%player_name%</aqua><green> użył teleportu, kosztowało go to</green> <gold>%cost%</gold>"
  shop:
    no_guild: "<red>Nie ma gildii - nie ma sklepu.</red>"
    title: "Guild shop"
    cost: "<white>Cost: </white><gold>%upgrade_cost%</gold>"
    upgrade_name: "<blue>%upgrade_name% %upgrade_level%</blue>"
    cannot_afford: "<red>Nie stać cię na to.</red>"
    max_level: "<yellow>Osiągnąłeś maksymalny poziom ulepszenia</yellow>"
    upgraded: "<green><aqua>%player_name%</aqua> ulepszył %upgrade_name% do poziomu %upgrade_level%</green>"
    bought: "<green><aqua>%player_name%</aqua> zakupił na własny użytek %hover_item%</green>"
  bank:
    no_guild: "<red>Nie ma gildii - nie ma banku.</red>"
    title: "Guild bank"
    tooltip_value: "<white>Value: </white><gold>%value%</gold>"
    tooltip_lmb: "<green>Left-Click to sell one</green>"
    tooltip_rmb: "<green>Right-Click to sell all</green>"
    material_absent: "<red>Nie masz tego materiału.</red>"
    deposit: "<aqua>%player_name%</aqua> <green>wpłacił do banku</green> <gold>%amount%</gold>"
  guild:
    tooltip_members: "<green>Members: </green>"
    tooltip_bank: "<white>Bank gildii: </white><gold>%guild_bank%</gold>"
    chat_enabled: "<green>Włączono czat gildii</green>"
    chat_disabled: "<red>Wyłączono czat gildii</red>"
    chat_unavailable: "<red>Nie jesteś w gildii, więc nie możesz pisać na czacie gildii.</red>"
  compass:
    name: "<aqua>Guild Compass</aqua>"
    tooltip_1: "<dark_green>Always points towards selected guild's heart</dark_green>"
    tooltip_2: "Selected guild: %guild%"
    title: "Select guild to track:"
    set_guild: "<green>Ustawiono gildię na</green> <gold>%guild%</gold>"
  guild_command:
    args_missing: "<red>Not enough arguments.</red>"
    data_saved: "<green>Zapisano dane gildii.</green>"
    data_loaded: "<green>Załadowano dane gildii.</green>"
    no_guild: "<red>Nic tu nie zdziałasz, bo w gildii nie jesteś.</red>"
    create_in_guild: "<red>Nie możesz utworzyć gildii, gdy jesteś już w jakiejś!</red>"
    create_args_missing: "<red>Podaj unikalne ID i nazwę dla twojej gildii!</red>"
    id_in_use: "<red>Gildia o podanym ID już istnieje</red>"
    created: "<green>Utworzyłeś gildię</green> <gold>%guild_id% (%guild_name%)</gold>"
    deleted: "<green>Gildia usunięta.</green>"
    invite_usage: "<yellow>Użycie: /guild invite <gracz></yellow>"
    presuffix_set: "<green>%presuffix% gildii ustawiony na </green><dark_aqua>%value%</dark_aqua>"
    unknown_color: "<red>Nieznany kolor: %color%</red>"
    color_reset: "<green>Kolor gildii zresetowany</green>"
    color_set: "<green>Kolor gildii ustawiony na</green> <%guild_color%>%guild_color%</%guild_color%>"
    name_set: "<green>Ustawiono nazwę gildii na</green> <gold>%guild_name%</gold>"
    icon_reset: "<green>Ikona gildii zresetowana</green>"
    unknown_material: "<red>Podaj prawidłową nazwę przedmiotu</red>"
    icon_set: "<green>Ikona gildii ustawiona na <hover:show_item:'%guild_icon_id%'>%guild_icon%</hover></green>"
    leave_notification: "<green>Gracz <aqua>%player_name%</aqua> opuszcza gildię!</green>"
  join:
    id_missing: "<red>Podaj ID gildii, do której chcesz dołączyć!</red>"
    unknown_guild: "<red>Nie znaleziono gildii.</red>"
    already_joined: "<yellow>Jesteś już członkiem gidii <gold>%guild_name%</gold></yellow>"
    already_in_guild: "<yellow>Jesteś już członkiem gidii <gold>%guild_name%</gold>. By dołączyć do <gold>%newguild_name%</gold>, musisz najpierw opuścić obecną. (/guild leave)</yellow>"
    no_invite: "<red>Nie masz zaproszenia do gildii <gold>%newguild_name%</gold>.</red>"
    notification: "<green>Gracz <aqua>%player_name%</aqua> dołączył do gildii!</green>"
    invite_notification: "<aqua>%inviter_name%</aqua><green> zaprosił gracza <aqua>%player_name%</aqua> do gildii!</green>"
    invited_no_inviter: "<green>Zostałeś zaproszony do gidii <gold>%newguild_name%</gold>. <blue><click:run_command:'/guild join %newguild_id%'>KLIKNIJ TUTAJ BY DOŁĄCZYĆ</click></blue></green>"
    invited_inviter: "<green>Zostałeś zaproszony przez <aqua>%inviter_name%</aqua> do gidii <gold>%newguild_name%</gold>. <blue><click:run_command:'/guild join %newguild_id%'>KLIKNIJ TUTAJ BY DOŁĄCZYĆ</click></blue></green>"
  heart:
    place: "<green>Gracz <aqua>%player_name%</aqua> postawił serce gildii!</green>"
    pickup: "<green>Gracz <aqua>%player_name%</aqua> podniósł serce gildii!</green>"
    destroy: "<dark_green>Serce gildii <gold>%targetguild_name%</gold> zostało zniszczone przez <aqua>%player_name%</aqua>!</dark_green>"
    entered_warning: "<aqua>%player_name%</aqua> <red>wszedł na teren gildii!</red>"
    container_locked: "<red>Nie możesz otwierać tu kontenerów</red>"
    chest_unbreakable: "<red>Nie możesz niszczyć tu skrzyń</red>"
    already_placed: "<red>Nie możesz postawić serca, gdy już jest jakieś postawione!</red>"
    placed_too_near: "<red>Nie możesz postawić serca, gdy w promieniu 24 chunków jest inna gildia!</red>"
    item_name: "<aqua>Guild Heart</aqua>"
    cannot_place_blocks: "<red>Nie możesz stawiać tu bloków</red>"
    nobody_online: "<red>Serce można zniszczyć tylko wtedy, gdy ktoś z gildii przeciwnej jest online.</red>"
# Coloring standard:
# Gold - guild
# Green - success notification
# Blue - clickable chat
# Aqua - Player names
# Red/Yellow - Errors