guild_chat_format: "<green>[GuildChat] </green><aqua><%player_name%></aqua> %message%"
heart_place_range: 384 # 16*24 blocks
allow_heart_destroy: true
tablist:
  header:
    - "        <gold>»»» MY-BEST-GUILD-SERVER-EVER «««</gold>        "
    - ""
  footer:
    - ""
    - "        <blue>Ping: %player_ping%ms</blue> | <green>PLAYERS ONLINE: %server_onlinecount%</green>        "
    - "<gold>Guild: %guild_name%</gold>"
    - "<white>Bank: </white><gold>%guild_bank%</gold>"
bank_materials:
  IRON_INGOT: 1
  GOLD_INGOT: 2
  DIAMOND: 20
  EMERALD: 5
  NETHERITE_SCRAP: 50
spawn: # some random coordinates I use for testing, you should put yours!
  world: world
  x1: -36
  z1: 210
  x2: 0
  z2: 241
upgrades:
  WORKING_RADIUS:
    name: "Working radius"
    description: "The heart main working radius, in multiples of 16"
    icon: SMITHING_TABLE
    slot: 19
    level_prices:
      - 0
      - 50
      - 100
      - 500
      - 1000
  WARNING_RADIUS:
    name: "Warning radius"
    description: "The heart warning radius, in multiples of 16"
    icon: ENDER_EYE
    slot: 20
    level_prices:
      - 100
      - 200
      - 500
  HEAL_RADIUS:
    name: "Healing radius"
    description: "The heart healing radius, in multiples of 16"
    icon: AMETHYST_CLUSTER
    slot: 21
    level_prices:
      - 100
      - 500
      - 1000
      - 1500
  MINING_FATIGUE:
    name: "Mining fatigue level"
    description: "The level of mining fatigue effect, applied in the working radius"
    icon: MINER_POTTERY_SHERD
    slot: 22
    level_prices:
      - 100
      - 500
      - 1000
  SLOWNESS:
    name: "Slowness level"
    description: "The level of slowness effect, applied in the working radius"
    icon: MUD
    slot: 23
    level_prices:
      - 100
      - 500
      - 1000
  CHEST_LOCK:
    name: "Chest locking"
    description: "Chest locking, applied in the working radius"
    icon: CHEST
    slot: 24
    level_prices:
      - 1000
items:
  GUILD_COMPASS:
    slot: 38
    cost: 750
  GUILD_HEART:
    slot: 42
    cost: 1500

tpa_delay: 5
tpa_cost: 10
back_cost: 20
